# Generated by Django 4.2.20 on 2025-04-10 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Camera",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("resolution", models.CharField(max_length=255)),
                ("features", models.CharField(max_length=255)),
                ("zoom", models.IntegerField()),
                ("software_features", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_name", models.CharField(max_length=255)),
                ("price", models.FloatField(default=0.0)),
                ("release_date", models.DateField()),
                ("slug", models.SlugField(unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="DeviceCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="DeviceFeatures",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("accessories", models.CharField(max_length=255)),
                ("seciurity", models.CharField(max_length=255)),
                ("warranty_and_support", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="DevicePhysicalInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("width", models.FloatField()),
                ("height", models.FloatField()),
                ("thickness", models.FloatField()),
                ("wireless_connectivity", models.CharField(max_length=255)),
                ("ports", models.CharField(max_length=255)),
                ("material", models.CharField(max_length=255)),
                ("device_color", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Display",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("size", models.CharField(max_length=255)),
                ("resolution", models.CharField(max_length=255)),
                ("protection", models.CharField(max_length=255)),
                ("technology", models.CharField(max_length=255)),
                ("refresh_rate", models.IntegerField()),
                ("brightness", models.IntegerField()),
                ("features", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="GraphicProcessor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("graphic_processor_name", models.CharField(max_length=255)),
                ("g_ram", models.IntegerField()),
                ("ram_type", models.CharField(max_length=255)),
                ("publishable", models.BooleanField(default=False)),
                ("slug", models.SlugField(unique=True)),
                ("release_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="OperatingSystem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("os_name", models.CharField(max_length=255)),
                ("kernel", models.CharField(max_length=255)),
                ("os_version", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("publishable", models.BooleanField(default=False)),
                ("slug", models.SlugField(unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Processor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("processor_name", models.CharField(max_length=255)),
                ("core", models.CharField(max_length=255)),
                ("refresh_rate", models.CharField(max_length=255)),
                ("cache", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("processor_technology", models.CharField(max_length=255)),
                ("slug", models.SlugField(unique=True)),
                ("publishable", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="DeviceSoftwareInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ui", models.CharField(max_length=255)),
                ("pre_installed_softwares", models.CharField(max_length=255)),
                ("update_policy", models.CharField(max_length=255)),
                ("customizability", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "os",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="device_software_info",
                        to="devices.operatingsystem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DeviceImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_image", models.ImageField(upload_to="device_images/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_images",
                        to="devices.device",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DeviceHardwareInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("battery", models.CharField(max_length=255)),
                ("memmory", models.IntegerField()),
                ("storage", models.CharField(max_length=255)),
                ("sensors", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "camera",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="device_hardware_info",
                        to="devices.camera",
                    ),
                ),
                (
                    "display",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="device_hardware_info",
                        to="devices.display",
                    ),
                ),
                (
                    "graphic_processor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="device_hardware_info",
                        to="devices.graphicprocessor",
                    ),
                ),
                (
                    "processor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="device_hardware_info",
                        to="devices.processor",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="device",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="devices",
                to="devices.devicecategory",
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="features",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="devices",
                to="devices.devicefeatures",
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="hardware_information",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="device",
                to="devices.devicehardwareinformation",
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="physical_information",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="device",
                to="devices.devicephysicalinformation",
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="software_information",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="device",
                to="devices.devicesoftwareinformation",
            ),
        ),
    ]
