# Generated by Django 4.2.20 on 2025-04-11 06:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("devices", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceResponse",
            fields=[],
            options={
                "verbose_name": "Device Response",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.response",),
        ),
        migrations.AddField(
            model_name="processor",
            name="release_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
