# Generated by Django 4.2.20 on 2025-04-11 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0002_deviceresponse_processor_release_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="devicefeatures",
            old_name="seciurity",
            new_name="security",
        ),
    ]
