# Generated by Django 4.2.20 on 2025-04-11 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0003_rename_seciurity_devicefeatures_security"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="device",
                to="devices.devicecategory",
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="features",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="device",
                to="devices.devicefeatures",
            ),
        ),
    ]
