# Generated by Django 4.2.20 on 2025-04-11 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0004_alter_device_category_alter_device_features"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="publishable",
            field=models.BooleanField(default=False),
        ),
    ]
