# Generated by Django 4.2.20 on 2025-04-10 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_profile_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                default="images/profiles/Default.jpg",
                upload_to="images/profiles",
            ),
        ),
    ]
