services:
  django:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.prod
    command: gunicorn account_service.wsgi:application --bind 0.0.0.0:8001 --workers 3 --log-level info
    volumes:
      - ..:/app
    ports:
      - "8001:8001"
    env_file:
      - ../env/.env.prod
    depends_on:
      - postgres
    networks:
      - backend

  postgres:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
    env_file:
      - ../env/.env.prod

  nginx:
    image: nginx:1.28.0
    container_name: account-nginx
    ports:
      - "80:80"
    depends_on:
      - django
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - backend
      - frontend
    restart: unless-stopped

networks:
  backend:
  frontend:

volumes:
  postgres_data:
