# Generated by Django 4.2.20 on 2025-04-10 17:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0005_alter_profile_profile_image"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60, unique=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60, unique=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="BlogResponse",
            fields=[],
            options={
                "verbose_name": "Blog Response",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.response",),
        ),
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=60, unique=True)),
                (
                    "banner",
                    models.ImageField(
                        blank=True,
                        default="images/Default_banner.jpg",
                        upload_to="images/",
                    ),
                ),
                ("content", models.TextField()),
                ("status", models.BooleanField(default=False)),
                ("views", models.PositiveIntegerField(default=0)),
                ("publishable", models.BooleanField(default=False)),
                ("slug", models.SlugField(max_length=60, unique=True)),
                (
                    "published_date",
                    models.DateField(blank=True, default=django.utils.timezone.now),
                ),
                ("update_date", models.DateTimeField(auto_now=True)),
                ("create_date", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.profile",
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True, related_name="blogs", to="blogs.category"
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="blogs", to="blogs.tag"
                    ),
                ),
            ],
        ),
    ]
