# Generated by Django 4.2.18 on 2025-01-28 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0002_category_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="description",
        ),
    ]
