# Generated by Django 4.2.18 on 2025-01-30 08:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0003_remove_category_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="published_date",
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
