# Generated by Django 4.2.18 on 2025-01-30 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0004_alter_blog_published_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="categories",
            field=models.ManyToManyField(
                blank=True, related_name="blogs", to="blogs.category"
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="blogs", to="blogs.tag"
            ),
        ),
    ]
