# Generated by Django 4.2.18 on 2025-01-30 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0005_alter_blog_categories_alter_blog_tags"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
    ]
