from .review_model import Review
from .graphic_processor_review_model import GraphicsProcessorReview
from .processor_review_model import ProcessorReview
from .operating_system_review_model import OperatingSystemReview
from .devices_review_model import DeviceReview
from .review_response_model import ReviewResponse
